### ISSUE TITLE
Tags filter doesn't wotk in Scoold webhooks

### ISSUE THREAD

**Issue by galshaked** [Erudika/scoold-pro#69]
I'm trying to create an integration between Scoold and Slack, to send notifications to Slack for a new question, only if a specific tag is included.
The integration works, but the filter doesn't (the notification has been sent, but even if the tag isn't included).
Steps to reproduce:
1. Create a new Slack webhook (based on the steps in this article https://scoold.com/slack.html)
2. Add a Property filter: tags:tag-test
3. Ask a question and DO NOT add this tag

**Comment by albogdano** [comment]
Just to be clear, do you add the property filter on ParaIO.com, under Settings > Webhooks? Slack webhooks in Scoold don't actually have a property filter.

**Comment by galshaked** [comment]
![Image](https://github.com/user-attachments/assets/35105384-b917-4d79-a5ed-b72789218fcc)

**Comment by albogdano** [comment]
ParaIO.com was updated recently with the new fix. The property filter should be working now.

**Comment by galshaked** [comment]
It is still not working. I'm still getting the notification even if the tag isn't included. 
Also, once in a while, all the settings in Scoold that connect to the Slack app disappear, and I need to set them from scratch.

**Comment by albogdano** [comment]
Those might be two separate issues. Where do you enter the configuration for Slack - on the Scoold Admin page or on Scoold Cloud?

**Comment by galshaked** [comment]
In the Scoold admin page

**Comment by albogdano** [comment]
I've just tested this and the Slack integration works as intended. What you are showing in the screenshot is a standard Scoold webhook which is configured to fire a payload to a Slack incoming webhook URL. The Slack software would not be able to parse the payload sent by Scoold. 
The property filter `tag:tag-test` would work only for the standard webhook and not for Slack webhooks. At least for now, there is no property filter input box for Slack/Teams/MM webhooks but that could be added easily in the future. The property filter also works as intended, at least for standard webhooks. I'm not sure how you see the payload in Slack without a configured Slack webhook in Scoold.

Here's where Slack webhooks are configured.

![Image](https://github.com/user-attachments/assets/055b92fc-eab7-4410-87d4-9e91fb05bfdd)

**Comment by albogdano** [comment]
Quick update - support for property filters in Slack/Teams/Mattermost webhooks has been implemented and is coming soon in the next version of Scoold Pro.

**Comment by albogdano** [comment]
Scoold `1.64.5` has been released - closing this issue.
